background            #161210
foreground            #f0e0d6
cursor                #e4572e
selection_background  #3a2e2a
selection_foreground  #ffffff

# Normal colors
color0                #ff1210
color1                #e4572e
color2                #88b04b
color3                #f4a259
color4                #a060ff
color5                #d86c9b
color6                #7bb2b0
color7                #e8dcd2

# Bright colors
color8                #7a665c
color9                #f55b3c
color10               #aad372
color11               #ffd580
color12               #72a1c0
color13               #ff99cc
color14               #a8dadc
color15               #fff8f0
